#!/bin/bash

input=$1
echo $input

if [[ $input = 'on' ]] ; then
    xrandr --output HDMI-2 --auto
    xrandr --output HDMI-3 --auto
    xrandr --output HDMI-3 --right-of HDMI-2 --rotate left
elif [[ $input = 'off' ]] ; then
    xrandr --output HDMI-3 --off
else
    echo "Use 'on' or 'off' as input."
fi
